export const types =  {
    
    ADD_TODO_STARTED : "ADD_TODO_STARTED",
    ADD_TODO_FAILURE: "ADD_TODO_FAILURE",
    ADD_TODO_SUCCESS : "ADD_TODO_SUCCESS",
    ADD_USER_CHOICE : "ADD_USER_CHOICE",
    NEXT_QUESTION : "NEXT_QUESTION",
    PREV_QUESTION :" PREV_QUESTION",
    VALIDATE_QUESTION : "VALIDATE_QUESTIONS",
    GOTO_HOME : "GOTO_HOME",
    RETRY : "RETRY",
    GOTO_SECTION : "GOTO_SECTION"


}